// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameInterfaceInfo = "interface_info"

// InterfaceInfo mapped from table <interface_info>
type InterfaceInfo struct {
	ID             int64     `gorm:"column:id;primaryKey;comment:主键" json:"id"`                                             // 主键
	Name           string    `gorm:"column:name;comment:名称" json:"name"`                                                    // 名称
	Description    string    `gorm:"column:description;comment:描述" json:"description"`                                      // 描述
	URL            string    `gorm:"column:url;not null;comment:接口地址" json:"url"`                                           // 接口地址
	RequestHeader  string    `gorm:"column:request_header;comment:请求头" json:"request_header"`                               // 请求头
	ResponseHeader string    `gorm:"column:response_header;comment:响应头" json:"response_header"`                             // 响应头
	Status         int32     `gorm:"column:status;not null;comment:接口状态(0-关闭， 1-开启)" json:"status"`                         // 接口状态(0-关闭， 1-开启)
	Method         string    `gorm:"column:method;not null;comment:请求类型" json:"method"`                                     // 请求类型
	UserID         int64     `gorm:"column:user_id;not null;comment:创建人" json:"user_id"`                                    // 创建人
	CreateTime     time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_time"` // 创建时间
	UpdateTime     time.Time `gorm:"column:update_time;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"update_time"` // 更新时间
	IsDelete       int32     `gorm:"column:is_delete;not null;comment:是否删除(0-未删除，1-删除)" json:"is_delete"`                   // 是否删除(0-未删除，1-删除)
}

// TableName InterfaceInfo's table name
func (*InterfaceInfo) TableName() string {
	return TableNameInterfaceInfo
}
