// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUser = "user"

// User mapped from table <user>
type User struct {
	ID           int64     `gorm:"column:id;primaryKey;comment:用户id" json:"id"`                                  // 用户id
	UserName     string    `gorm:"column:user_name;not null;comment:用户名不允许重复" json:"user_name"`                  // 用户名不允许重复
	AvatarURL    string    `gorm:"column:avatar_url;comment:用户头像" json:"avatar_url"`                             // 用户头像
	UserPassword string    `gorm:"column:user_password;not null;comment:用户密码" json:"user_password"`              // 用户密码
	CreateTime   time.Time `gorm:"column:create_time;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_time"` // 创建时间
	UpdateTime   time.Time `gorm:"column:update_time;default:CURRENT_TIMESTAMP;comment:更新时间" json:"update_time"` // 更新时间
	IsDelete     int32     `gorm:"column:is_delete;not null;comment:是否删除,0为不删除，1为删除" json:"is_delete"`           // 是否删除,0为不删除，1为删除
	UserRole     string    `gorm:"column:user_role;comment:用户类型，有user,admin,ban" json:"user_role"`               // 用户类型，有user,admin,ban
	AccessKey    string    `gorm:"column:accessKey;comment:本平台的accessKey" json:"accessKey"`                      // 本平台的accessKey
	SecretKey    string    `gorm:"column:secretKey;comment:本平台的secretKey" json:"secretKey"`                      // 本平台的secretKey
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
